### ISSUE TITLE
The extensions don't work on both Firefox and Chrome

### ISSUE THREAD

**Issue by grenvol** [alexbarrett/analyse-chesstempo-on-lichess#1]
The extensions don't work on both Firefox and Chrome.

Maybe Richard broke them on purpose? Anyway, It'd be nice to bring back this extension to life

**Comment by alexbarrett** [comment]
It probably was not on purpose; it's been a long time since I updated this so I'm not surprised to hear it's no longer working.

**Comment by grenvol** [comment]
He was not happy with such extensions on reddit [link](https://old.reddit.com/r/chess/comments/7toi54/lichess_analysis_links_on_chesstempo/dtejreo/).

Do you plan to fix it?

**Comment by alexbarrett** [comment]
I've released v1.0.1. Grab it from the [release page](https://github.com/alexbarrett/analyse-chesstempo-on-lichess/releases).
