### ISSUE TITLE
The knight analyze icon is not as well placed like in the screenshot

### ISSUE THREAD

**Issue by grenvol** [alexbarrett/analyse-chesstempo-on-lichess#3]
Screenshot in the github page, how It's supposed to look like?
![screenshot](https://user-images.githubusercontent.com/70918865/92992697-1382ff00-f4ed-11ea-8b25-7109f4443e0e.png)

How It really looks like (tested on both Google chrome and Firefox):

![black knight](https://user-images.githubusercontent.com/70918865/92992717-37464500-f4ed-11ea-9ac8-a2883adef21e.png)

Placing it in a better place (either like the screenshot or another well aligned place with a good size) could add some polish.

**Comment by alexbarrett** [comment]
This is due to a bug in the ChessTempo code base. The 'after' parameter to the board-controls element doesn't work because of an incorrect selector (`.class[attr]` instead of `.class [attr]`).
