### ISSUE TITLE
The icon show up when selecting a set

### ISSUE THREAD

**Issue by grenvol** [alexbarrett/analyse-chesstempo-on-lichess#8]
Steps to reproduce: Go to https://chesstempo.com/chess-tactics, when selecting the difficulty and set of problems, the icon show up:
![startup screen](https://user-images.githubusercontent.com/70918865/92993535-a6726800-f4f2-11ea-89d9-10bf454823d2.png)

It's more of an UX problem than a clear cut problem.

Pros of keeping it: We can know and be sure that the extension is working properly before even starting the puzzle
Cons: It takes some screen estate for a useless button. 
Some users may think that It's a bug and the button will stay there even after the puzzle starts.

**Comment by alexbarrett** [comment]
The visibility of the Lichess analysis button is tied to the visibility of ChessTempo's own analysis button. This is so the extension can avoid having its own logic for when the button should be shown. The ChessTempo analysis button is visible in your screenshot so I'm going to say this is working as intended.
